name: egi_replay_env
channels:
  - conda-forge
  - coecms
  - defaults
dependencies:
  - python=3.10
  - cartopy
  - cf_xarray
  - cmocean
  - cosima-cookbook
  - dask
  - distributed
  - eofs
  - intake
  - matplotlib
  - numpy
  - scikit-learn
  - scipy
  - xarray
  - ipykernel
